### ISSUE TITLE
Filenotfounderror

### ISSUE THREAD

**Issue by dabenik** [fritzlb/iOS17-JIT-WIN#24]
I folowed all the steps in the video and I used the right command with the right bundle id (python jit_enabler_better.py net.kdt.pojavlauncher.7L94YGFAK8)

This is the error that I got:
Traceback (most recent call last):
  File "C:\Users\Myname\DOWNLO~1\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 129, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Myname\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Myname\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by fritzlb** [comment]
Try running install_slow.bat, then execute the python command again

**Comment by dabenik** [comment]
> Try running install_slow.bat, then execute the python command again

That doens't work, I get the exact same error message

**Comment by fritzlb** [comment]
The error occurs when the script is trying to attach the debugger to the App because it can’t find that. Install and install_slow do use different methods to unpack a downloaded archive, so both not working is weird. Was your PC connected to the internet as you executed those scripts? Also, is there a chance your system is modified in a way that powershell is blocked or sth?
As a last resort you can always open one of the scripts in a text editor and manually download and extract the archive linked there, make sure to extract it in a way that the llvm folder is inside the folder the script is in and that the bin folder is directly in the llvm folder :)

**Comment by fritzlb** [comment]
I assume everything works for you by now, if not, feel free to re-open this (or create a new one if the issue isn’t related) :)
