### ISSUE TITLE
Failed to connect to usbmuxd socket. Make sure it's running.

### ISSUE THREAD

**Issue by hyhcrh** [fritzlb/iOS17-JIT-WIN#35]
E:\IOS17-~1>python jit_enabler_better.py com.utmapp.UTM.4G354BN73Q True
Getting bundle ID...
DEBUG mode specified.
Got bundle ID: com.utmapp.UTM.4G354BN73Q
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: xxx 51723
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
2024-04-13 17:51:53 XXX __main__[22144] ERROR Failed to connect to usbmuxd socket. Make sure it's running.

Error mounting DiskImage : 2024-04-13 17:51:53 XXX__main__[22144] ERROR Failed to connect to usbmuxd socket. Make sure it's running.

iPadOS 17.3, Windows 10 22H2 (Sorry I don't have a 11 PC)
I have read #17 and added True to the end of the command, but it didn't work.
Checked cable quality.
iTunes was installed from Apple.
WiFi is on.

Please help.

**Comment by fritzlb** [comment]
Thank you for all the information, this makes the whole process a lot faster! Adding True to the end of the command intheory shouldn’t change anything except for extended debug messages.

Usually this issue appears when iTunes is installed from the Microsoft store and not directly from Apple but you stated you downloaded it directly from Apple without touching MS store, so that’s obviously not the case. 

Windows 10 should be fine. Also, just to make sure, iTunes connects to your device, right?

If I interpret the log correctly pymobiledevice3 (the library doing most of the heavy lifting) can‘t connect to the usbmuxd socket that connects to your device. It might be that for whatever reason usbmuxd hasn’t been started properly, starting iTunes before running the script or rebooting might fix that. Could you maybe try that and report back?

**Comment by hyhcrh** [comment]
Thank you for your quick reply!
Well, it's really lucky of me to fix this issue by myself.
I've checked all issues related to any errors when executing the script.
Really lucky, I checked #1 and found [this comment](https://github.com/fritzlb/iOS17-JIT-WIN/issues/1#issuecomment-1980127408)
So I just followed the instrutions and run all python commands in the source code, and it succeeded.
I just changed a line of the source code, and it was tested successful on my computer. I finally have my UTM virtual machine started in the standard version of UTM (JIT required), which substantiates my effort.
I have just created a pull request for this. Hope it can help!
